//
// Created by hiddenst on 19.03.23.
//

#ifndef BICYCLE_FUTURE_INCLUDE_BICYCLE_FUTURE_INL_HPP_
#define BICYCLE_FUTURE_INCLUDE_BICYCLE_FUTURE_INL_HPP_

#endif  // BICYCLE_FUTURE_INCLUDE_BICYCLE_FUTURE_INL_HPP_
